version: '3'

services:

  postgres-db:
    image: postgres:latest
    container_name: postgres-cont
    build:
       context: ./
       dockerfile: ./db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USERNAME: 'postgres'


  jdbc-app:
    image: jdbc-java
    container_name: jdbc-cont
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8282:8080"
